---
abstract: 'IRC frontend to Acme::MetaSyntactic'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  File::Find: 0
  List::Util: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-Module-MetaSyntactic
requires:
  Acme::MetaSyntactic: 0
  Bot::BasicBot::Pluggable::Module: 0
  Carp: 0
  Text::Wrap: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Bot-BasicBot-Pluggable-Module-MetaSyntactic
  repository: http://github.com/book/Bot-BasicBot-Pluggable-Module-MetaSyntactic.git
version: 1.002
